// Mocks generated by Mockito 5.4.6 from annotations
// in sparkle_lite/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sparkle_lite/core_import.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSymptomRepository_2 extends _i1.SmartFake
    implements _i2.SymptomRepository {
  _FakeSymptomRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUsecase extends _i1.Mock implements _i2.LoginUsecase {
  MockLoginUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i3.Future<_i2.ApiResult<_i2.AuthUserEntity>> call(_i2.LoginParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i2.ApiResult<_i2.AuthUserEntity>>.value(
              _FakeApiResult_1<_i2.AuthUserEntity>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i2.ApiResult<_i2.AuthUserEntity>>);
}

/// A class which mocks [SignUpUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUsecase extends _i1.Mock implements _i2.SignUpUsecase {
  MockSignUpUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i3.Future<_i2.ApiResult<_i2.AuthUserEntity>> call(
    _i2.SignUpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i2.ApiResult<_i2.AuthUserEntity>>.value(
              _FakeApiResult_1<_i2.AuthUserEntity>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i2.ApiResult<_i2.AuthUserEntity>>);
}

/// A class which mocks [LogoutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUsecase extends _i1.Mock implements _i2.LogoutUsecase {
  MockLogoutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i3.Future<_i2.ApiResult<void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_1<void>(this, Invocation.method(#call, [])),
            ),
          )
          as _i3.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [FetchSymptomLogsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchSymptomLogsUsecase extends _i1.Mock
    implements _i2.FetchSymptomLogsUsecase {
  MockFetchSymptomLogsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SymptomRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSymptomRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SymptomRepository);

  @override
  _i3.Future<_i2.ApiResult<List<_i2.SymptomLogEntity>>> call(
    _i2.FetchSymptomLogsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i2.ApiResult<List<_i2.SymptomLogEntity>>>.value(
                  _FakeApiResult_1<List<_i2.SymptomLogEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResult<List<_i2.SymptomLogEntity>>>);
}

/// A class which mocks [DeleteSymptomLogUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteSymptomLogUsecase extends _i1.Mock
    implements _i2.DeleteSymptomLogUsecase {
  MockDeleteSymptomLogUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SymptomRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSymptomRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SymptomRepository);

  @override
  _i3.Future<_i2.ApiResult<void>> call(_i2.DeleteSymptomLogParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_1<void>(this, Invocation.method(#call, [params])),
            ),
          )
          as _i3.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [FetchProfileSettingsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchProfileSettingsUsecase extends _i1.Mock
    implements _i2.FetchProfileSettingsUsecase {
  MockFetchProfileSettingsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResult<_i2.ProfileSettingsEntity>> call(
    _i2.FetchProfileParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i2.ApiResult<_i2.ProfileSettingsEntity>>.value(
                  _FakeApiResult_1<_i2.ProfileSettingsEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResult<_i2.ProfileSettingsEntity>>);
}

/// A class which mocks [UpdatePrivacySettingsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePrivacySettingsUsecase extends _i1.Mock
    implements _i2.UpdatePrivacySettingsUsecase {
  MockUpdatePrivacySettingsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResult<void>> call(_i2.UpdatePrivacyParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_1<void>(this, Invocation.method(#call, [params])),
            ),
          )
          as _i3.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [AddFamilyMemberUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFamilyMemberUsecase extends _i1.Mock
    implements _i2.AddFamilyMemberUsecase {
  MockAddFamilyMemberUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResult<void>> call(_i2.AddFamilyMemberParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_1<void>(this, Invocation.method(#call, [params])),
            ),
          )
          as _i3.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [RemoveFamilyMemberUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFamilyMemberUsecase extends _i1.Mock
    implements _i2.RemoveFamilyMemberUsecase {
  MockRemoveFamilyMemberUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResult<void>> call(_i2.RemoveFamilyMemberParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_1<void>(this, Invocation.method(#call, [params])),
            ),
          )
          as _i3.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [SignOutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUsecase extends _i1.Mock implements _i2.SignOutUsecase {
  MockSignOutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResult<void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_1<void>(this, Invocation.method(#call, [])),
            ),
          )
          as _i3.Future<_i2.ApiResult<void>>);
}
