name: sparkle_lite
description: "Sparkle Lite is a Flutter application that provides a lightweight and efficient solution for managing your tasks and to-do lists. With its intuitive interface and powerful features, Sparkle Lite helps you stay organized and productive throughout the day."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
 # DI
  get_it: ^9.2.1
  injectable: ^2.4.4

  # Routing
  auto_route: ^11.1.0

  # Network
  dio: ^5.7.0

  # Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^10.0.0

 #Firebase
  firebase_core: ^4.8.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  firebase_messaging: ^16.2.0

  flutter_local_notifications: ^21.0.0
  connectivity_plus: ^7.1.1
  lottie: ^3.3.3
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.4
  screenshot: ^3.0.0
  path_provider: ^2.1.2

  share_plus: ^12.0.2
  file_picker: ^11.0.2

  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.4.4
  auto_route_generator: ^10.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F820A5"
  adaptive_icon_foreground: "assets/logo.png" 

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/logo.png

    - assets/icons/common/
  # Auth 
    - assets/icons/auth/
    - .env
