// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNAvIH8xYnof_BDFH54YIg4HYv6uk3ZXc',
    appId: '1:247606471711:web:8ab2734d5075e46032792a',
    messagingSenderId: '247606471711',
    projectId: 'qr-gift-system-a4830',
    authDomain: 'qr-gift-system-a4830.firebaseapp.com',
    storageBucket: 'qr-gift-system-a4830.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMY9P_aMVXgCGX65uDJQ-rjGX4RACMacg',
    appId: '1:247606471711:android:22eabe65a789f8c832792a',
    messagingSenderId: '247606471711',
    projectId: 'qr-gift-system-a4830',
    storageBucket: 'qr-gift-system-a4830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrVR3WnoMn1SQg9YiRIxfczbJhy4uOmQ',
    appId: '1:247606471711:ios:4806f90aa8c4c71e32792a',
    messagingSenderId: '247606471711',
    projectId: 'qr-gift-system-a4830',
    storageBucket: 'qr-gift-system-a4830.firebasestorage.app',
    iosBundleId: 'com.dailycoll.dailyFinanceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrVR3WnoMn1SQg9YiRIxfczbJhy4uOmQ',
    appId: '1:247606471711:ios:4806f90aa8c4c71e32792a',
    messagingSenderId: '247606471711',
    projectId: 'qr-gift-system-a4830',
    storageBucket: 'qr-gift-system-a4830.firebasestorage.app',
    iosBundleId: 'com.dailycoll.dailyFinanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNAvIH8xYnof_BDFH54YIg4HYv6uk3ZXc',
    appId: '1:247606471711:web:102376a018b55ade32792a',
    messagingSenderId: '247606471711',
    projectId: 'qr-gift-system-a4830',
    authDomain: 'qr-gift-system-a4830.firebaseapp.com',
    storageBucket: 'qr-gift-system-a4830.firebasestorage.app',
  );
}
