// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjDzrPbMdqvyOVThScA-porG2ZOroYeC0',
    appId: '1:327706044489:web:258d9d501598588210f798',
    messagingSenderId: '327706044489',
    projectId: 'sparkle-lite',
    authDomain: 'sparkle-lite.firebaseapp.com',
    storageBucket: 'sparkle-lite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN0gPrcO9P-GdZEvfuPn11vG87OiQ0vo0',
    appId: '1:327706044489:android:5d437f1177680eff10f798',
    messagingSenderId: '327706044489',
    projectId: 'sparkle-lite',
    storageBucket: 'sparkle-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARKY9I1j7_tSkuNDfPj-oA8SVMBigbs_w',
    appId: '1:327706044489:ios:85d6a25da2b54e8710f798',
    messagingSenderId: '327706044489',
    projectId: 'sparkle-lite',
    storageBucket: 'sparkle-lite.firebasestorage.app',
    iosBundleId: 'sparkle-lite.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrVR3WnoMn1SQg9YiRIxfczbJhy4uOmQ',
    appId: '1:247606471711:ios:4806f90aa8c4c71e32792a',
    messagingSenderId: '247606471711',
    projectId: 'qr-gift-system-a4830',
    storageBucket: 'qr-gift-system-a4830.firebasestorage.app',
    iosBundleId: 'sparkle-lite.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjDzrPbMdqvyOVThScA-porG2ZOroYeC0',
    appId: '1:327706044489:web:36454251e17519d110f798',
    messagingSenderId: '327706044489',
    projectId: 'sparkle-lite',
    authDomain: 'sparkle-lite.firebaseapp.com',
    storageBucket: 'sparkle-lite.firebasestorage.app',
  );
}
